version: "3"
services:
  hacker-api:
    build: ./api/
    volumes:
      - ./api:/cruzhacks/api/
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    container_name: "database"
    
