version: "3"

services:
  hacker-api:
    container_name: "hacker-api"
    build: ./hacker_api/
    volumes:
      - ./hacker_api:/cruzhacks/api/
    ports:
      - "300:300"
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.4-jessie
    container_name: "hacker-database"
    networks:
      - backend

networks:
  backend:
