version: "3"
services:
  hacker-api:
    build: ./hacker_api/
    volumes:
      - ./hacker_api:/cruzhacks/api/
    ports:
      - "300:300"
  mongodb:
    image: mongo:latest
    container_name: "database"

